name: 'Configure Git'
description: 'Configure git credentials and extract repository name'
inputs:
  BUILD_PATH:
    description: 'Path to the build directory'
    required: true
  GIT_USER:
    description: 'Username for git'
    required: true
  GIT_EMAIL:
    description: 'Email for git'
    required: true
outputs:
  repo_name:
    description: 'Repository name extracted from the GitHub repository'
    value: ${{ steps.get-repo.outputs.repo_name }}
  binary_name: 
    description: 'Binary name extracted from the GitHub repository'
    value: ${{ steps.check-git-diff.outputs.binary_name }}
  new_version:
    description: 'New version of the binary'
    value: ${{ steps.check-git-diff.outputs.new_version }}
  update_artifacts:
    description: 'Flag to update artifacts_to_deploy.yml'
    value: ${{ steps.check-git-diff.outputs.update_artifacts }}

runs:
  using: 'composite'
  steps:
    - name: Set up Git
      run: |
        git config --global user.name "${{ inputs.GIT_USER }}"
        git config --global user.email "${{ inputs.GIT_EMAIL }}"
      shell: bash
        
    - name: Extract repository name
      id: get-repo
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        echo "repository=${REPO_NAME}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Checkout Repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 2

    - name: RENAME COBOL Directory
      run: |
        cd ${{ github.workspace }}/ES
        mkdir -p COBOL-sources
        mv COBOL/* COBOL-sources
      shell: bash

    - name: Determine changed files and update binary versions
      id: check-git-diff
      run: ${{ github.action_path }}/git-diff.sh "${{ github.workspace }}/ES/COBOL-sources" "${{ github.workspace }}/ES/COBOL" "${{ github.run_id }}" "${{ github.action_path }}"
      shell: bash
