name: Reusable Configure Git Workflow

on:
  workflow_call:
    inputs:
      BUILD_PATH:
        required: true
        type: string
    secrets:
      GIT_USER:
        required: true
      GIT_EMAIL:
        required: true
    outputs:
      repo_name: 
        value: ${{ jobs.configure-git.outputs.repo_name }}
      binary_name: 
        value: ${{ jobs.configure-git.outputs.binary_name }}
      new_version: 
        value: ${{ jobs.configure-git.outputs.new_version }}
      update_artifacts: 
        value: ${{ jobs.configure-git.outputs.update_artifacts }}


jobs:
  configure-git:
    runs-on: cobol
    outputs:
      repo_name: ${{ steps.check-git-diff.outputs.repository }}
      binary_name: ${{ steps.check-git-diff.outputs.binary }}
      new_version: ${{ steps.check-git-diff.outputs.version }}
      update_artifacts: ${{ steps.check-git-diff.outputs.changes_found }}
    steps:
      - uses: davidcambrils25/bash-repo-management/.github/actions/configure-git@main
        with:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        id: check-git-diff