name: Reusable Deploy Artifacts Workflow

on:
  workflow_call:
    inputs:
      RUN_ID:
        required: true
        type: string
      ARTIFACT_NAME:
        required: true
        type: string
      ARTIFACT_VERSION:
        required: true
        type: string
      BUILD_PATH:
        required: true
        type: string
      DEPLOYMENT_PATH:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

jobs:
  deploy-artifacts:
    runs-on: cobol
    steps:
      - name: Download artifacts
        env: 
          RUN_ID: ${{ inputs.RUN_ID }}
          ARTIFACT_NAME: ${{ inputs.ARTIFACT_NAME }}
          ARTIFACT_VERSION: ${{ inputs.ARTIFACT_VERSION }}
          DEPLOYMENT_PATH: ${{ inputs.DEPLOYMENT_PATH }}
        run: |
          cd ${{ inputs.BUILD_PATH }}/cicd_scripts/
          chmod +x ./deploy.sh
          ./deploy.sh "${{ github.repository_owner }}" "${{ needs.configure-git.outputs.repo_name }}" "$RUN_ID" "${{ secrets.GH_PAT }}" "$ARTIFACT_NAME" "$ARTIFACT_VERSION" "$DEPLOYMENT_PATH"
      
      - name: Update artifacts_to_deploy.yml
        env:
          BINARY_NAME: ${{ inputs.ARTIFACT_NAME }}
          VERSION: ${{ inputs.ARTIFACT_VERSION }}
          DEPLOYMENT_PATH: ${{ inputs.DEPLOYMENT_PATH }}
        run: |
          cd ${{ inputs.BUILD_PATH }}/cicd_scripts/
          chmod +x ./artifacts_to_deploy.sh
          ./artifacts_to_deploy.sh $BINARY_NAME $VERSION ${{ inputs.BUILD_PATH }} $DEPLOYMENT_PATH

      - name: Commit changes
        run: |
          cd ${{ inputs.BUILD_PATH }}
          git add artifacts_to_deploy.yml
          git commit -m "Automated updated artifacts_version.yaml by GitHub Actions workflow"
          git push https://${{ secrets.GIT_USER }}:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/${{ inputs.REPO_MANAGEMENT }}.git HEAD:main
          

